// Brand ActionTypes.
export const BRAND_REQUEST = "BRAND_REQUEST";
export const BRAND_REQUEST_SUCCESS = "BRAND_REQUEST_SUCCESS";
export const BRAND_REQUEST_FAIELD = "BRAND_REQUEST_FAIELD";

export const BRAND_CREATE_SUCCESS = "BRAND_CREATE_SUCCESS";
export const BRAND_CREATE_FAIELD = "BRAND_CREATE_FAIELD";

export const BRAND_DELETE_SUCCESS = "BRAND_DELETE_SUCCESS";
export const BRAND_DELETE_FAIELD = "BRAND_DELETE_FAIELD";

export const BRAND_STATUS_UPDATE = "BRAND_STATUS_UPDATE";

export const BRAND_UPDATE_SUCCESS = "BRAND_UPDATE_SUCCESS";
export const BRAND_UPDATE_FAIELD = "BRAND_UPDATE_FAIELD";

