// Brand ActionTypes.
export const BRAND_REQUEST = "BRAND_REQUEST";
export const BRAND_REQUEST_SUCCESS = "BRAND_REQUEST_SUCCESS";
export const BRAND_REQUEST_FAIELD = "BRAND_REQUEST_FAIELD";

export const BRAND_CREATE_SUCCESS = "BRAND_CREATE_SUCCESS";
export const BRAND_CREATE_FAIELD = "BRAND_CREATE_FAIELD";

export const BRAND_DELETE_SUCCESS = "BRAND_DELETE_SUCCESS";
export const BRAND_DELETE_FAIELD = "BRAND_DELETE_FAIELD";

export const BRAND_STATUS_UPDATE_SUCCESS = "BRAND_STATUS_UPDATE_SUCCESS";
export const BRAND_STATUS_UPDATE_FAIELD = "BRAND_STATUS_UPDATE_FAIELD";

export const BRAND_UPDATE_SUCCESS = "BRAND_UPDATE_SUCCESS";
export const BRAND_UPDATE_FAIELD = "BRAND_UPDATE_FAIELD";

// Tag ActionTypes.
export const TAG_REQUEST = "TAG_REQUEST";
export const TAG_REQUEST_SUCCESS = "TAG_REQUEST_SUCCESS";
export const TAG_REQUEST_FAIELD = "TAG_REQUEST_FAIELD";

export const CREATE_TAG_REQUEST = "CREATE_TAG_REQUEST";
export const CREATE_TAG_REQUEST_SUCCESS = "CREATE_TAG_REQUEST_SUCCESS";
export const CREATE_TAG_REQUEST_FAIELD = "CREATE_TAG_REQUEST_FAIELD";

export const TAG_STATUS_UPDATE_SUCCESS = "TAG_STATUS_UPDATE_SUCCESS";
export const TAG_STATUS_UPDATE_FAIELD = "TAG_STATUS_UPDATE_FAIELD";

export const TAG_UPDATE_SUCCESS = "TAG_UPDATE_SUCCESS";
export const TAG_UPDATE_FAIELD = "TAG_UPDATE_FAIELD";

export const TAG_DELETE_SUCCESS = "TAG_DELETE_SUCCESS";
export const TAG_DELETE_FAIELD = "TAG_DELETE_FAIELD";

// Category Actions Types.
export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_REQUEST_SUCCESS = "CATEGORY_REQUEST_SUCCESS";
export const CATEGORY_REQUEST_FAIELD = "CATEGORY_REQUEST_FAIELD";

export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_FAIELD = "CATEGORY_CREATE_FAIELD";

export const CATEGORY_STATUS_UPDATE_SUCCESS = "CATEGORY_STATUS_UPDATE_SUCCESS";
export const CATEGORY_STATUS_UPDATE_FAIELD = "CATEGORY_STATUS_UPDATE_FAIELD";

export const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_FAIELD = "CATEGORY_UPDATE_FAIELD";

export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAIELD = "CATEGORY_DELETE_FAIELD";

